// Divisiones federativas: ficha, validación de servidor, búsqueda, cartel e historial.
import { datosDeAlta, B, rnd, browser, seen, check, newUser, registrar, sql, enDias, terminarDiagnosticos } from "./ayudas.mjs";
const junior="RFE2026:Júnior:M", cadete="RFE2026:Cadete / Schoolboys–Schoolgirls:M", benjamin="RFE2026:Benjamín:M";
const formButton=(p,name)=>p.locator("main form").filter({has:p.getByRole("button",{name,exact:true})});
const disciplina=(p)=>p.locator('main details').filter({has:p.locator('summary strong',{hasText:/^Boxeo$/})});
async function create(name,division,peso) {
  const u=await newUser(name,"FIGHTER");
  await u.p.goto(B+"/mi-ficha");
  await datosDeAlta(u.p);
  const f=formButton(u.p,"Crear mi ficha");
  await f.locator("[name=firstName]").fill(name); await f.locator("[name=lastName]").fill(`Divisiones${rnd}`);
  if (division) await f.locator("[name=divisionId]").selectOption(division);
  if (peso) await f.locator("[name=weightClass]").selectOption(peso);
  await f.getByRole("button",{name:"Crear mi ficha",exact:true}).click();
  await u.p.getByRole("link",{name:"Ver mi ficha pública",exact:true}).waitFor();
  u.publica=await u.p.getByRole("link",{name:"Ver mi ficha pública",exact:true}).getAttribute("href");
  return u;
}
async function birth(u,date) {
  const d=u.p.locator("main details").filter({has:u.p.locator('[name=birthDate]')});
  if (!await d.getAttribute("open")) await d.locator("summary").click();
  await d.locator('[name=birthDate]').fill(date);
  await d.getByRole("button",{name:"Guardar los datos de mi ficha",exact:true}).click();
  await u.p.locator('[role=status]',{hasText:"Los datos de tu ficha se han guardado"}).waitFor();
}
const a=await create("JuniorCategorias",junior,"M66");
const b=await create("RivalCategorias",null,null);
const form=disciplina(a.p);
await form.locator("summary").click();
check("júnior ofrece 13 pesos más la opción sin confirmar",await form.locator('[name=weightClass] option').count()===14);
await form.locator('[name=divisionId]').selectOption(cadete);
check("cambiar de división borra el peso y ofrece la tabla schoolboys",await form.locator('[name=weightClass]').inputValue()==="" && await form.locator('[name=weightClass] option').count()===18);
await form.locator('[name=divisionId]').selectOption(junior);
await form.locator('[name=weightClass]').evaluate(el=>{el.add(new Option("Peso manipulado","M65"));el.value="M65";});
await form.getByRole("button",{name:"Guardar cambios",exact:true}).click();
await a.p.locator('[role=alert]',{hasText:"categoría"}).waitFor();
check("el servidor rechaza un peso de élite falsificado como júnior",true);
await a.p.goto(B+"/mi-ficha");
await birth(a,"2011-12-31"); await birth(b,"2012-01-01");
const editarB=disciplina(b.p);
await editarB.locator('summary').click();await editarB.locator('[name=divisionId]').selectOption(junior);await editarB.locator('[name=weightClass]').selectOption("M60");
await editarB.getByRole('button',{name:"Guardar cambios",exact:true}).click();await b.p.locator('[role=alert]',{hasText:"no coincide"}).waitFor();
check("la ficha también rechaza un grupo incompatible con el nacimiento declarado",true);
const fan=await newUser("FanCategorias");
await fan.p.goto(B+`/peleadores?disciplina=BOXEO&level=AMATEUR&divisionId=${encodeURIComponent(junior)}&categoria=M66&q=Divisiones${rnd}`);
check("búsqueda combina división y peso en la misma disciplina",await seen(fan.p.getByRole("link",{name:/JuniorCategorias/})) && !await seen(fan.p.getByRole("link",{name:/RivalCategorias/})));
const org=await newUser("OrganizadorCategorias");
sql(`UPDATE "User" SET role='ORGANIZER' WHERE email='${org.email}';`);
await org.p.goto(B+"/organizador");
await org.p.locator('[name=name]').fill(`Divisiones cartel ${rnd}`); await org.p.locator('[name=date]').fill(enDias(-1));
await datosDeAlta(org.p);
await org.p.getByRole("button",{name:"Crear el evento",exact:true}).click(); await org.p.waitForURL('**/organizador/*');
const cartel=formButton(org.p,"Añadir al cartel");
const valor=async (name,text)=>cartel.locator(`[name=${name}]`).evaluate((el,text)=>[...el.options].find(o=>o.textContent.includes(text))?.value,text);
const aid=await valor("fighterA",`JuniorCategorias Divisiones${rnd}`), bid=await valor("fighterB",`RivalCategorias Divisiones${rnd}`);
// El identificador ya elegido en el cartel también permite probar el POST de un peleador contra un rival conocido.
await a.p.goto(B+"/mi-ficha");
const propio=formButton(a.p,"Registrar este combate");
await propio.locator('[name=divisionId]').selectOption(junior);await propio.locator('[name=weightClass]').selectOption("M66");
await propio.evaluate((form,id)=>{const el=document.createElement('input');el.type='hidden';el.name='rivalId';el.value=id;form.append(el);},bid);
await registrar(a.p,{evento:`Edades propias ${rnd}`,fecha:enDias(-1),rivalNombre:"RivalCategorias",rivalApellidos:`Divisiones${rnd}`,resultado:"WIN",metodo:"UD"});
await a.p.locator('[role=alert]',{hasText:"edad"}).waitFor();
check("el registro del peleador también comprueba la edad conocida del rival",true);
await cartel.locator('[name=fighterA]').selectOption(aid); await cartel.locator('[name=fighterB]').selectOption(bid);
await cartel.locator('[name=divisionId]').selectOption(junior);await cartel.locator('[name=weightClass]').selectOption("M66");
await cartel.getByRole("button",{name:"Añadir al cartel",exact:true}).click();
await org.p.locator('[role=alert]',{hasText:"edad"}).waitFor();
check("el cartel rechaza una pareja de edades incompatibles aunque el peso coincida",true);
await b.p.goto(B+"/mi-ficha");await birth(b,"2011-01-01");
await cartel.locator('[name=fighterA]').selectOption(aid); await cartel.locator('[name=fighterB]').selectOption(bid);
await cartel.locator('[name=divisionId]').selectOption(junior);await cartel.locator('[name=weightClass]').selectOption("M66");
await cartel.getByRole("button",{name:"Añadir al cartel",exact:true}).click();
const fila=org.p.locator('tbody tr',{hasText:"JuniorCategorias"});await fila.waitFor();
check("el organizador guarda edad, sexo y peso propios de ese combate",(await fila.innerText()).includes("Júnior (15–16 años)") && (await fila.innerText()).includes("66 kg"));
await fila.locator('[name=outcome]').selectOption("WIN"); await fila.locator('[name=method]').selectOption("UD");
await fila.getByRole("button",{name:/^Guardar resultado de/}).click();
await org.p.locator('[role=status]',{hasText:"El resultado se ha guardado"}).waitFor();
const editarEvento=formButton(org.p,"Guardar los datos de la velada");
await org.p.locator('main details').filter({has:org.p.locator('summary',{hasText:/^Corregir los datos de la velada/})}).locator('summary').click();await editarEvento.locator('[name=date]').fill("2027-02-01");
await editarEvento.getByRole('button',{name:"Guardar los datos de la velada",exact:true}).click();
await org.p.locator('[role=alert]',{hasText:"año de reglamento"}).waitFor();
check("corregir la fecha no cambia en silencio el año de una división guardada",true);
await fan.p.goto(B+a.publica);
await fan.p.getByRole("button",{name:/Dar aura/}).click();
await fan.p.getByRole("button",{name:/Quitar mi aura/}).waitFor();
await a.p.goto(B+"/mi-ficha");
const editar=disciplina(a.p);
await editar.locator('summary').click();await editar.locator('[name=weightClass]').selectOption("M60");await editar.getByRole('button',{name:"Guardar cambios",exact:true}).click();
await a.p.locator('main details summary',{hasText:'hasta 60 kg'}).waitFor();
await fan.p.goto(B+"/ranking?disciplina=BOXEO");
const grupo=fan.p.locator('main section').filter({has:fan.p.getByRole('heading',{name:/Júnior.*hasta 66 kg/})});
check("actualizar el peso de la ficha no mueve el aura histórica a otra categoría",await seen(grupo.getByRole('link',{name:`JuniorCategorias Divisiones${rnd}`,exact:true})));
await fan.p.goto(B+a.publica);
check("la ficha pública conserva la división del combate junto a su peso histórico",await seen(fan.p.locator('#combates article',{hasText:/Júnior.*66 kg/})));
const datos=await (await a.p.request.get(B+"/mi-cuenta/datos")).json();
check("la descarga distingue la división actual y la de cada combate",datos.fichaDePeleador.disciplinas[0].divisionDeportiva===junior && datos.fichaDePeleador.disciplinas[0].categoria==="M60" && datos.combatesDeMiFicha.some(b=>b.divisionDeportiva===junior&&b.categoria==="M66"));
const c=await create("FormacionCategorias",benjamin,null);
const editarFormacion=disciplina(c.p);await editarFormacion.locator('summary').click();
check("benjamín carece de pesos y se explica que es solo formación",await editarFormacion.locator('[name=weightClass] option').count()===1 && await seen(editarFormacion.getByText(/Solo formación/).first()));
await registrar(c.p,{evento:`Formación prohibida ${rnd}`,fecha:enDias(2),rivalNombre:"Rival",rivalApellidos:`Formacion${rnd}`,resultado:null});
await c.p.locator('[role=alert]',{hasText:"no permite combates"}).waitFor();
check("el servidor impide registrar combates de una ficha benjamín",true);
await c.p.goto(B+"/mi-ficha");await birth(c,"2017-01-01");
const formacion=disciplina(c.p);await formacion.locator('summary').click();
await formacion.locator('[name=divisionId]').selectOption("");await formacion.getByRole('button',{name:"Guardar cambios",exact:true}).click();
await c.p.locator('[role=status]',{hasText:"Se ha guardado la disciplina en tu ficha"}).waitFor();
await registrar(c.p,{evento:`Edad no eludible ${rnd}`,fecha:enDias(2),rivalNombre:"Rival",rivalApellidos:`Edad${rnd}`,resultado:null});
await c.p.locator('[role=alert]',{hasText:"edad"}).waitFor();
check("una edad benjamín conocida no elude la prohibición dejando la división vacía",true);
const otra=c.p.locator('main details').filter({has:c.p.locator('summary strong',{hasText:/^Añadir otra disciplina$/})});await otra.locator('summary').click();
await otra.locator('[name=discipline]').selectOption("K1");await otra.locator('[name=divisionId]').selectOption("WAKO2022-K1:Ring · Júnior joven:F");
check("K-1 muestra los pesos femeninos júnior de ring",await otra.locator('[name=weightClass] option').count()===9 && await otra.locator('[name=weightClass] option[value=F36]').count()===1);
await otra.locator('[name=discipline]').selectOption("MMA");await otra.locator('[name=divisionId]').selectOption("IMMAF2026:Youth C:F");
check("MMA juvenil no hereda los pesos masculinos adultos",await otra.locator('[name=weightClass] option').count()===1 && await seen(otra.getByText(/Pesos no catalogados/).first()));
await otra.locator('[name=discipline]').selectOption("JIUJITSU");await otra.locator('[name=divisionId]').selectOption("IBJJF2024:Mighty Mite I:F");
check("jiu-jitsu infantil explica las dimensiones que faltan sin ofrecer pesos adultos",await otra.locator('[name=weightClass] option').count()===1 && await seen(otra.getByText(/kimono\/sin kimono y cinturón/).first()));
await browser.close();await terminarDiagnosticos();
