// Personalización persistente, permisos y graduación, con imágenes reales y PostgreSQL.
import { PrismaClient } from '@prisma/client';
import sharp from 'sharp';
import AxeBuilder from '@axe-core/playwright';
import { B, rnd, browser, newUser, btn, check, seen, terminarDiagnosticos } from './ayudas.mjs';
const db = new PrismaClient();
const own = await newUser('Perfil', 'FIGHTER');
await own.p.goto(B + '/mi-ficha');
await own.p.fill('[name=firstName]', 'Perfil');
await own.p.fill('[name=lastName]', `Personal${rnd}`);
await own.p.selectOption('select[name=discipline]', 'JIUJITSU');
await own.p.selectOption('select[name=province]', 'Madrid');
await own.p.selectOption('[name=belt]', 'PURPLE');
await own.p.fill('[name=beltDegrees]', '2');
await btn(own.p, 'Crear mi ficha');
await own.p.locator('.notice-ok').waitFor();
const f = await db.fighter.findFirstOrThrow({where:{lastName:`Personal${rnd}`}});
const edit = `/perfiles/peleador/${f.id}/editar`;
const image = await sharp({create:{width:700,height:400,channels:3,background:'#be33f5'}}).png().toBuffer();
await own.p.goto(B + edit);
await own.p.setInputFiles('[name=avatar]', {name:'foto.png',mimeType:'image/png',buffer:image});
await own.p.setInputFiles('[name=banner]', {name:'banner.png',mimeType:'image/png',buffer:image});
await own.p.locator('[name=avatarX]').focus();
await own.p.locator('[name=avatarX]').press('Home');
await own.p.locator('[name=avatarX]').press('ArrowRight');
await btn(own.p, 'Guardar perfil');
check('La personalización confirma el guardado', await seen(own.p.locator('.notice-ok')));
const saved = await db.profile.findUniqueOrThrow({where:{kind_entityId:{kind:'peleador',entityId:f.id}}});
check('Foto y banner se almacenan optimizados con su encuadre', saved.hasAvatar && saved.hasBanner && saved.avatarX === 1 && saved.avatar.length > 0);
const anon = await (await browser.newContext()).newPage();
await anon.goto(B + `/peleadores/${f.slug}`);
check('La ficha muestra el cinturón declarado', (await anon.locator('main').innerText()).includes('Cinturón morado · 2 grados'));
const photo = await anon.request.get(B + `/imagenes/peleador/${f.id}/avatar`);
check('La imagen pública responde como WebP', photo.ok() && photo.headers()['content-type'] === 'image/webp');
const etag = photo.headers()['etag'];
const repetida = await anon.request.get(B + `/imagenes/peleador/${f.id}/avatar`, { headers: { 'If-None-Match': etag ?? '' } });
check('Quien ya tiene la imagen recibe un 304 sin bytes (no se vuelve a leer de la base de datos)', !!etag && repetida.status() === 304 && (await repetida.body()).length === 0);
check('y la imagen se revalida siempre y no se guarda en cachés compartidas', /private/.test(photo.headers()['cache-control'] ?? '') && /no-cache/.test(photo.headers()['cache-control'] ?? ''));
const other = await newUser('Ajeno');
await other.p.goto(B + edit);
check('Otra cuenta no puede editar este perfil', other.p.url().includes('/mi-cuenta?problema=sin_permiso'));
await own.p.goto(B + edit);
await own.p.check('[name=removeAvatar]'); await own.p.check('[name=removeBanner]');
await btn(own.p, 'Guardar perfil');
await own.p.locator('.notice-ok').waitFor();
const removed = await db.profile.findUniqueOrThrow({where:{kind_entityId:{kind:'peleador',entityId:f.id}}});
check('Quitar las imágenes elimina los bytes y las marcas públicas', removed.avatar === null && removed.banner === null && !removed.hasAvatar && !removed.hasBanner);
await db.fighter.update({where:{id:f.id},data:{hiddenAt:new Date()}});
check('Una ficha ocultada no publica su imagen', (await anon.request.get(B + `/imagenes/peleador/${f.id}/avatar`)).status() === 404);
await db.fighter.update({where:{id:f.id},data:{hiddenAt:null}});
// Entidades: el moderador asigna al titular, que puede personalizar las tres clases.
const admin = await newUser('PerfilAdmin');
await db.user.update({where:{email:admin.email},data:{role:'ADMIN'}});
const gym = await db.gym.create({data:{name:`Gym Perfil ${rnd}`,slug:`gym-perfil-${rnd}`,city:'Madrid',province:'Madrid'}});
const trainer = await db.trainer.create({data:{name:`Entrenador Perfil ${rnd}`,slug:`entrenador-perfil-${rnd}`,gymId:gym.id}});
await admin.p.goto(B + '/federaciones');
await admin.p.fill('main [name=name]', `Federación Perfil ${rnd}`);
await btn(admin.p, 'Crear perfil de federación');
await admin.p.waitForURL('**/perfiles/federacion/*/editar');
const fed = await db.profile.findFirstOrThrow({where:{kind:'federacion',name:`Federación Perfil ${rnd}`}});
for (const [kind,id,publicPath] of [['gimnasio',gym.id,`/gimnasios/${gym.slug}`],['entrenador',trainer.id,`/entrenadores/${trainer.slug}`],['federacion',fed.entityId,`/federaciones/${fed.entityId}`]]) {
  const path = `/perfiles/${kind}/${id}/editar`;
  await admin.p.goto(B + path);
  await admin.p.fill('[name=ownerEmail]', other.email);
  await btn(admin.p, 'Guardar perfil'); await admin.p.locator('.notice-ok').waitFor();
  await other.p.goto(B + path);
  const axe = await new AxeBuilder({page:other.p}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();
  check(`El editor de ${kind} no tiene fallos graves de accesibilidad`, !axe.violations.some(v => v.impact === 'serious' || v.impact === 'critical'));
  await other.p.fill('[name=bio]', `Presentación de ${kind}`);
  await other.p.setInputFiles('[name=avatar]', {name:'logo.png',mimeType:'image/png',buffer:image});
  await other.p.setInputFiles('[name=banner]', {name:'portada.png',mimeType:'image/png',buffer:image});
  await btn(other.p, 'Guardar perfil'); await other.p.locator('.notice-ok').waitFor();
  await anon.goto(B + publicPath);
  check(`El titular de ${kind} publica foto, banner y presentación`, (await anon.locator('main').innerText()).includes(`Presentación de ${kind}`) && await anon.locator('.profile-avatar img').count() === 1 && await anon.locator('.profile-banner').count() === 1);
  await own.p.goto(B + path);
  check(`Otra cuenta no puede editar ${kind}`, own.p.url().includes('/mi-cuenta?problema=sin_permiso'));
}
await db.user.update({where:{email:other.email},data:{role:'ORGANIZER'}});
const promoter = await db.user.findUniqueOrThrow({where:{email:other.email}});
await other.p.goto(B + `/perfiles/promotor/${promoter.id}/editar`);
await other.p.setInputFiles('[name=banner]', {name:'portada.png',mimeType:'image/png',buffer:image});
await btn(other.p, 'Guardar perfil'); await other.p.locator('.notice-ok').waitFor();
await anon.goto(B + `/promotores/${promoter.id}`);
check('El promotor puede publicar su banner', await anon.locator('.profile-banner').count() === 1);
await terminarDiagnosticos(); await browser.close(); await db.$disconnect();
